Landingzone solution
aliyun/alibabacloud-landing-zone pull request #4
Opened 2021-01-26 11:24 UTC by tianma168

add multi account multi vpc network solution

2021-01-27 01:52 UTC, wibud approved these changes

2021-02-01 09:19 UTC, daxingplay commented on solution/networking/multi-account-multi-vpc/versions.tf
> +      version = ">= 1.96.0"
```suggestion
      version = ">= 1.114.0"
```

1.96.0 还不支持 Enhanced 的 NAT Gateway

2021-02-01 09:25 UTC, daxingplay commented on solution/networking/multi-account-multi-vpc/network/project/nat/main.tf
> +
好像没有创建 SNAT 规则？

2021-02-01 09:26 UTC, daxingplay requested changes
好像 NAT 那里没有创建 SNAT 规则？

2021-02-04 03:16 UTC, merged